[project]
name = "tinyllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "thop>=0.1.1.post2209072238",
    "tiktoken>=0.12.0",
    "tqdm>=4.67.1",
]
